# Generated by Django 5.0.6 on 2024-05-22 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Customer',
            fields=[
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=11)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('accounts_cnt', models.IntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='BankCustomer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
