# Generated by Django 5.0.6 on 2024-06-03 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_department',
            name='department_manager',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 6, 3, 14, 33, 30, 932993)),
        ),
    ]
