# Generated by Django 5.0.6 on 2024-06-03 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0002_alter_bank_department_department_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_department',
            name='department_manager',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 6, 3, 16, 36, 54, 540400)),
        ),
    ]
