# Generated by Django 5.0.6 on 2024-05-27 08:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0003_customer_account_loan_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 27, 16, 12, 34, 291130)),
        ),
    ]
