# Generated by Django 5.0.6 on 2024-05-29 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0004_alter_loan_loan_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 29, 21, 7, 22, 199487)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('收入', '收入'), ('支出', '支出')], default='支出', max_length=100),
        ),
    ]
