# Generated by Django 5.0.6 on 2024-05-29 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0005_alter_loan_loan_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 29, 23, 56, 41, 674430)),
        ),
    ]
