# Generated by Django 5.0.6 on 2024-05-31 04:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBankSystem', '0006_alter_loan_loan_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='loan_deadline',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 31, 12, 22, 19, 668457)),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0.0)),
                ('transaction_type', models.CharField(choices=[('收入', '收入'), ('支出', '支出')], default='支出', max_length=100)),
                ('transaction_detail', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Transactions', to='myBankSystem.customer_account')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
